stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
# Build stage
build:
  stage: build
  image: docker:latest
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
    - develop

# Unit test stage
unit_tests:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
    - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  script:
    - pytest tests/test_for_predictornew.py
  only:
    - merge_requests
    - develop
    - main

# Integration test stage
integration_tests:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
    - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  script:
    - pytest tests/test_for_integ.py
  only:
    - merge_requests
    - develop
    - main

# Deployment stage
deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker pull $DOCKER_IMAGE
    - docker run -d -p 8000:8000 $DOCKER_IMAGE
  only:
    - main

