services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NAME=TitanicSurvival
      - PYTHONPATH=/app
  test:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app  
    command: ["pytest", "tests/"]